//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTree.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertClassEstimationEntity
    {
        public long ExpertClassEstimationId { get; set; }
        public long TreeEventId { get; set; }
        public long ExpertId { get; set; }
        public Nullable<double> WaterLevel { get; set; }
        public byte MinEstimation { get; set; }
        public byte MaxEstimation { get; set; }
        public byte AverageEstimation { get; set; }
        public long Order { get; set; }
    
        public virtual TreeEventEntity TreeEventEntity { get; set; }
        public virtual ExpertEntity ExpertEntity { get; set; }
    }
}
