//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTree.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpertEntity()
        {
            this.ExpertClassEstimationEntities = new HashSet<ExpertClassEstimationEntity>();
        }
    
        public long ExpertId { get; set; }
        public long PersonId { get; set; }
        public string Expertise { get; set; }
        public string Organisation { get; set; }
        public long ProjectId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertClassEstimationEntity> ExpertClassEstimationEntities { get; set; }
        public virtual ProjectEntity ProjectEntity { get; set; }
        public virtual PersonEntity PersonEntity { get; set; }
    }
}
