//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTree.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragilityCurveElementEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FragilityCurveElementEntity()
        {
            this.HydraulicConditionElementEntities = new HashSet<HydraulicConditionElementEntity>();
            this.TreeEventFragilityCurveElementEntities = new HashSet<TreeEventFragilityCurveElementEntity>();
        }
    
        public long FragilityCurveElementId { get; set; }
        public Nullable<double> WaterLevel { get; set; }
        public Nullable<double> Probability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HydraulicConditionElementEntity> HydraulicConditionElementEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreeEventFragilityCurveElementEntity> TreeEventFragilityCurveElementEntities { get; set; }
    }
}
