//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTree.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HydraulicConditionElementEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HydraulicConditionElementEntity()
        {
            this.ExpertClassEstimationEntities = new HashSet<ExpertClassEstimationEntity>();
        }
    
        public long HydraulicConditionElementId { get; set; }
        public long FragilityCurveElementId { get; set; }
        public long ProjectId { get; set; }
        public Nullable<double> WavePeriod { get; set; }
        public Nullable<double> WaveHeight { get; set; }
        public long Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertClassEstimationEntity> ExpertClassEstimationEntities { get; set; }
        public virtual FragilityCurveElementEntity FragilityCurveElementEntity { get; set; }
        public virtual ProjectEntity ProjectEntity { get; set; }
    }
}
