//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTree.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectEntity()
        {
            this.EventTreeEntities = new HashSet<EventTreeEntity>();
            this.ExpertEntities = new HashSet<ExpertEntity>();
            this.HydraulicConditionElementEntities = new HashSet<HydraulicConditionElementEntity>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string AssessmentSection { get; set; }
        public string ProjectInformation { get; set; }
        public Nullable<long> ProjectLeaderId { get; set; }
        public long ProjectId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTreeEntity> EventTreeEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertEntity> ExpertEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HydraulicConditionElementEntity> HydraulicConditionElementEntities { get; set; }
        public virtual PersonEntity PersonEntity { get; set; }
    }
}
