//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTree.Storage.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventTreeEntity> EventTreeEntities { get; set; }
        public virtual DbSet<ExpertClassEstimationEntity> ExpertClassEstimationEntities { get; set; }
        public virtual DbSet<ExpertEntity> ExpertEntities { get; set; }
        public virtual DbSet<FragilityCurveElementEntity> FragilityCurveElementEntities { get; set; }
        public virtual DbSet<HydraulicConditionElementEntity> HydraulicConditionElementEntities { get; set; }
        public virtual DbSet<PersonEntity> PersonEntities { get; set; }
        public virtual DbSet<ProjectEntity> ProjectEntities { get; set; }
        public virtual DbSet<TreeEventEntity> TreeEventEntities { get; set; }
        public virtual DbSet<TreeEventFragilityCurveElementEntity> TreeEventFragilityCurveElementEntities { get; set; }
    }
}
