//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTree.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionEntity
    {
        public long VersionId { get; set; }
        public string Version { get; set; }
        public string TimeStamp { get; set; }
        public byte[] FingerPrint { get; set; }
    }
}
